import {
  BookOpen,
  Brain,
  Code,
  Globe,
  Music,
  PenTool,
  Gamepad2,
  Trophy,
  GraduationCap,
  Calculator,
  FlaskConical,
  Atom,
  Palette,
  Film,
  Dumbbell,
  Heart,
  History,
  Lightbulb,
  Map,
  Shield,
  Star,
  TreeDeciduous,
  User,
  Wand2,
  Zap,
} from "lucide-react";

export const quizIcons = [
  { name: "BookOpen", icon: BookOpen },
  { name: "Brain", icon: Brain },
  { name: "Code", icon: Code },
  { name: "Globe", icon: Globe },
  { name: "Music", icon: Music },
  { name: "PenTool", icon: PenTool },
  { name: "Gamepad2", icon: Gamepad2 },
  { name: "Trophy", icon: Trophy },
  { name: "GraduationCap", icon: GraduationCap },
  { name: "Calculator", icon: Calculator },
  { name: "FlaskConical", icon: FlaskConical },
  { name: "Atom", icon: Atom },
  { name: "Palette", icon: Palette },
  { name: "Film", icon: Film },
  { name: "Dumbbell", icon: Dumbbell },
  { name: "Heart", icon: Heart },
  { name: "History", icon: History },
  { name: "Lightbulb", icon: Lightbulb },
  { name: "Map", icon: Map },
  { name: "Shield", icon: Shield },
  { name: "Star", icon: Star },
  { name: "TreeDeciduous", icon: TreeDeciduous },
  { name: "User", icon: User },
  { name: "Wand2", icon: Wand2 },
  { name: "Zap", icon: Zap },
];
